add support for private git repos and npm registries
Private git repos can be accessed by providing path to .netrc file. The
file needs to be added to extra-sandbox-paths, and if daemon is used
appropriate permissions need to be set on it.

Private npm registries are supported via tokens passed in as files
(which need to be added to sandbox as above), which are then
turned into env variables. The env variable can then be used in
.yarnrc.yml to set npmAuthToken via env variable interpolation

diff --git a/src/tmpl/yarn-project.nix.in b/src/tmpl/yarn-project.nix.in
--- a/src/tmpl/yarn-project.nix.in
+++ b/src/tmpl/yarn-project.nix.in
@@ -1,8 +1,8 @@
 # This file is generated by running "yarn install" inside your project.
 # Manual changes might be lost - proceed with caution!
 
-{ lib, nodejs, stdenv, fetchurl, writeText, git, cacert }:
-{ src, overrideAttrs ? null, ... } @ args:
+{ lib, nodejs, stdenv, fetchurl, writeText, writeShellScriptBin, git, cacert, gnused }:
+{ src, symlinkPackages ? false, overrideAttrs ? null, netrcFilePath ? null, secretsEnvVars ? null, ... } @ args:
 
 let
 
@@ -30,20 +30,81 @@ let
     '';
   };
 
+  checkSandboxPathExists = writeShellScriptBin "check-sandbox-file-exists" ''
+    set -ueo pipefail
+
+    file_path=$1
+
+    if ! test -e "$file_path"
+    then
+      echo >&2 "Error: $file_path does not exist or cannot be accessed due to permissions!"
+      echo >&2 "  Make sure it's added to extra-sandbox-paths and that nixbld"
+      echo >&2 "  user group has read access to it."
+      exit 1
+    fi
+  '';
+
+  linkNetrcFile = writeShellScriptBin "link-netrc-file" ''
+    set -ueo pipefail
+
+    netrc_file_path=$1
+    home=$2
+
+    ${checkSandboxPathExists}/bin/check-sandbox-file-exists "$netrc_file_path"
+
+    if ! test -d "$home";
+    then
+      echo >&2 "given HOME path (''${home}) does not exist or is not a directory"
+      exit 1
+    fi
+
+    echo >&2 "linking .netrc file at ''${netrc_file_path} to ''${home}"
+
+    ln -s "$netrc_file_path" "$home"
+  '';
+
+  exportEnvVarsFromFilesIfAny = envVarNamesToPaths:
+    if envVarNamesToPaths != null
+    # build a list of export statement
+    then lib.concatStringsSep "\n" (lib.mapAttrsToList
+      (name: path: ''
+        check-sandbox-file-exists "${path}"
+        export ${name}=$(cat "${path}")
+      '')
+      envVarNamesToPaths
+    )
+    else ""
+  ;
+
   # Create derivations for fetching dependencies.
   cacheDrvs = let
     builder = builtins.toFile "builder.sh" ''
       source $stdenv/setup
+
+      ${exportEnvVarsFromFilesIfAny secretsEnvVars}
+
+      home=$TMP
+      yarn_cache_folder=$home/cache
+      mkdir -p $yarn_cache_folder
+
+      ${
+        if netrcFilePath != null
+        then ''link-netrc-file "${netrcFilePath}" "$home"''
+        else ""
+      }
+
       cd "$src"
-      HOME="$TMP" yarn_cache_folder="$TMP" CI=1 \
-        node '${yarnPath}' nixify fetch-one $locator
+      HOME="$home" yarn_cache_folder="$yarn_cache_folder" CI=1 \
+         node '${yarnPath}' nixify fetch-one $locator
       # Because we change the cache dir, Yarn may generate a different name.
-      mv "$TMP/$(sed 's/-[^-]*\.[^-]*$//' <<< "$outputFilename")"-* $out
+      mv "$yarn_cache_folder/$(sed 's/-[^-]*\.[^-]*$//' <<< "$outputFilename")"-* $out
     '';
   in lib.mapAttrs (locator: { filename, sha512 }: stdenv.mkDerivation {
     inherit src builder locator;
     name = lib.strings.sanitizeDerivationName locator;
     buildInputs = [ nodejs git cacert ];
+    buildInputs = [ nodejs ];
+    nativeBuildInputs = [ git cacert linkNetrcFile checkSandboxPathExists ];
     outputFilename = filename;
     outputHashMode = "flat";
     outputHashAlgo = "sha512";
